name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile SCSS into CSS
        uses: gha-utilities/sass-build@v0.4.3
        with:
          source: styles.scss
          destination: styles.css
          
      - name: Add and commit changes
        run: |
          git config --global user.email 'action@github.com'
          git config --global user.name 'Github action'
          git add -A
          git commit -m 'Update compiled CSS files'
          git push
