name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile SCSS into CSS
        uses: gha-utilities/sass-build@v0.4.3
        with:
          source: styles.scss
          destination: styles.css
          
      - name: Config email
        run: git config --local user.email 'action@github.com'
      - name: Config username
        run: git config --local user.name 'Github action'
      - name: Add and commit changes
        run: git commit -m 'Update compiled CSS files' -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
